# Generated by Django 6.0.1 on 2026-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('education', 'Éducation'), ('sante', 'Santé'), ('environnement', 'Environnement'), ('social', 'Social')], max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='realisations/')),
            ],
        ),
    ]
