# Generated by Django 6.0.2 on 2026-02-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='image',
        ),
        migrations.AlterField(
            model_name='realisation',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='impact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='RealisationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realisations/')),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realisations.realisation')),
            ],
        ),
    ]
