# Generated by Django 6.0.1 on 2026-02-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partenaires/')),
                ('site_web', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
