# Generated by Django 6.0.1 on 2026-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
